package com.maserven.modelos;
// Generated Nov 20, 2017 3:07:33 PM by Hibernate Tools 4.3.1



/**
 * ScgColores generated by hbm2java
 */
public class ScgColores  implements java.io.Serializable {


     private String scgColCodigo;
     private String scgColDescripcion;

    public ScgColores() {
    }

    public ScgColores(String scgColCodigo, String scgColDescripcion) {
       this.scgColCodigo = scgColCodigo;
       this.scgColDescripcion = scgColDescripcion;
    }
   
    public String getScgColCodigo() {
        return this.scgColCodigo;
    }
    
    public void setScgColCodigo(String scgColCodigo) {
        this.scgColCodigo = scgColCodigo;
    }
    public String getScgColDescripcion() {
        return this.scgColDescripcion;
    }
    
    public void setScgColDescripcion(String scgColDescripcion) {
        this.scgColDescripcion = scgColDescripcion;
    }




}


