package com.maserven.modelos;
// Generated Nov 20, 2017 3:07:33 PM by Hibernate Tools 4.3.1



/**
 * ScgConfig generated by hbm2java
 */
public class ScgConfig  implements java.io.Serializable {


     private char scgSisCodigo;
     private String scgSisNombre;
     private String scgSisVersion;
     private char scgSisDbms;
     private short scgSisLicencias;
     private String scgSisPaginaWeb;
     private boolean scgSisMensajeria;
     private String scgSisServer;

    public ScgConfig() {
    }

    public ScgConfig(char scgSisCodigo, String scgSisNombre, String scgSisVersion, char scgSisDbms, short scgSisLicencias, String scgSisPaginaWeb, boolean scgSisMensajeria, String scgSisServer) {
       this.scgSisCodigo = scgSisCodigo;
       this.scgSisNombre = scgSisNombre;
       this.scgSisVersion = scgSisVersion;
       this.scgSisDbms = scgSisDbms;
       this.scgSisLicencias = scgSisLicencias;
       this.scgSisPaginaWeb = scgSisPaginaWeb;
       this.scgSisMensajeria = scgSisMensajeria;
       this.scgSisServer = scgSisServer;
    }
   
    public char getScgSisCodigo() {
        return this.scgSisCodigo;
    }
    
    public void setScgSisCodigo(char scgSisCodigo) {
        this.scgSisCodigo = scgSisCodigo;
    }
    public String getScgSisNombre() {
        return this.scgSisNombre;
    }
    
    public void setScgSisNombre(String scgSisNombre) {
        this.scgSisNombre = scgSisNombre;
    }
    public String getScgSisVersion() {
        return this.scgSisVersion;
    }
    
    public void setScgSisVersion(String scgSisVersion) {
        this.scgSisVersion = scgSisVersion;
    }
    public char getScgSisDbms() {
        return this.scgSisDbms;
    }
    
    public void setScgSisDbms(char scgSisDbms) {
        this.scgSisDbms = scgSisDbms;
    }
    public short getScgSisLicencias() {
        return this.scgSisLicencias;
    }
    
    public void setScgSisLicencias(short scgSisLicencias) {
        this.scgSisLicencias = scgSisLicencias;
    }
    public String getScgSisPaginaWeb() {
        return this.scgSisPaginaWeb;
    }
    
    public void setScgSisPaginaWeb(String scgSisPaginaWeb) {
        this.scgSisPaginaWeb = scgSisPaginaWeb;
    }
    public boolean isScgSisMensajeria() {
        return this.scgSisMensajeria;
    }
    
    public void setScgSisMensajeria(boolean scgSisMensajeria) {
        this.scgSisMensajeria = scgSisMensajeria;
    }
    public String getScgSisServer() {
        return this.scgSisServer;
    }
    
    public void setScgSisServer(String scgSisServer) {
        this.scgSisServer = scgSisServer;
    }




}


