package com.maserven.modelos;
// Generated Nov 20, 2017 3:07:33 PM by Hibernate Tools 4.3.1



/**
 * ScgMensajesId generated by hbm2java
 */
public class ScgMensajesId  implements java.io.Serializable {


     private short scgMenAnio;
     private String scgUsuCodigo;
     private long scgMenNumero;

    public ScgMensajesId() {
    }

    public ScgMensajesId(short scgMenAnio, String scgUsuCodigo, long scgMenNumero) {
       this.scgMenAnio = scgMenAnio;
       this.scgUsuCodigo = scgUsuCodigo;
       this.scgMenNumero = scgMenNumero;
    }
   
    public short getScgMenAnio() {
        return this.scgMenAnio;
    }
    
    public void setScgMenAnio(short scgMenAnio) {
        this.scgMenAnio = scgMenAnio;
    }
    public String getScgUsuCodigo() {
        return this.scgUsuCodigo;
    }
    
    public void setScgUsuCodigo(String scgUsuCodigo) {
        this.scgUsuCodigo = scgUsuCodigo;
    }
    public long getScgMenNumero() {
        return this.scgMenNumero;
    }
    
    public void setScgMenNumero(long scgMenNumero) {
        this.scgMenNumero = scgMenNumero;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ScgMensajesId) ) return false;
		 ScgMensajesId castOther = ( ScgMensajesId ) other; 
         
		 return (this.getScgMenAnio()==castOther.getScgMenAnio())
 && ( (this.getScgUsuCodigo()==castOther.getScgUsuCodigo()) || ( this.getScgUsuCodigo()!=null && castOther.getScgUsuCodigo()!=null && this.getScgUsuCodigo().equals(castOther.getScgUsuCodigo()) ) )
 && (this.getScgMenNumero()==castOther.getScgMenNumero());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getScgMenAnio();
         result = 37 * result + ( getScgUsuCodigo() == null ? 0 : this.getScgUsuCodigo().hashCode() );
         result = 37 * result + (int) this.getScgMenNumero();
         return result;
   }   


}


