package com.maserven.modelos;
// Generated Nov 20, 2017 3:07:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ScgModulos generated by hbm2java
 */
public class ScgModulos  implements java.io.Serializable {


     private char scgModCodigo;
     private String scgModDescripcion;
     private char scgModEstado;
     private Date scgModFechaAct;
     private Date scgModFechaVal;
     private String scgModSerialAct;
     private String scgModSerialVal;
     private Set scgProgramases = new HashSet(0);

    public ScgModulos() {
    }

	
    public ScgModulos(char scgModCodigo, String scgModDescripcion, char scgModEstado, Date scgModFechaAct, Date scgModFechaVal, String scgModSerialAct, String scgModSerialVal) {
        this.scgModCodigo = scgModCodigo;
        this.scgModDescripcion = scgModDescripcion;
        this.scgModEstado = scgModEstado;
        this.scgModFechaAct = scgModFechaAct;
        this.scgModFechaVal = scgModFechaVal;
        this.scgModSerialAct = scgModSerialAct;
        this.scgModSerialVal = scgModSerialVal;
    }
    public ScgModulos(char scgModCodigo, String scgModDescripcion, char scgModEstado, Date scgModFechaAct, Date scgModFechaVal, String scgModSerialAct, String scgModSerialVal, Set scgProgramases) {
       this.scgModCodigo = scgModCodigo;
       this.scgModDescripcion = scgModDescripcion;
       this.scgModEstado = scgModEstado;
       this.scgModFechaAct = scgModFechaAct;
       this.scgModFechaVal = scgModFechaVal;
       this.scgModSerialAct = scgModSerialAct;
       this.scgModSerialVal = scgModSerialVal;
       this.scgProgramases = scgProgramases;
    }
   
    public char getScgModCodigo() {
        return this.scgModCodigo;
    }
    
    public void setScgModCodigo(char scgModCodigo) {
        this.scgModCodigo = scgModCodigo;
    }
    public String getScgModDescripcion() {
        return this.scgModDescripcion;
    }
    
    public void setScgModDescripcion(String scgModDescripcion) {
        this.scgModDescripcion = scgModDescripcion;
    }
    public char getScgModEstado() {
        return this.scgModEstado;
    }
    
    public void setScgModEstado(char scgModEstado) {
        this.scgModEstado = scgModEstado;
    }
    public Date getScgModFechaAct() {
        return this.scgModFechaAct;
    }
    
    public void setScgModFechaAct(Date scgModFechaAct) {
        this.scgModFechaAct = scgModFechaAct;
    }
    public Date getScgModFechaVal() {
        return this.scgModFechaVal;
    }
    
    public void setScgModFechaVal(Date scgModFechaVal) {
        this.scgModFechaVal = scgModFechaVal;
    }
    public String getScgModSerialAct() {
        return this.scgModSerialAct;
    }
    
    public void setScgModSerialAct(String scgModSerialAct) {
        this.scgModSerialAct = scgModSerialAct;
    }
    public String getScgModSerialVal() {
        return this.scgModSerialVal;
    }
    
    public void setScgModSerialVal(String scgModSerialVal) {
        this.scgModSerialVal = scgModSerialVal;
    }
    public Set getScgProgramases() {
        return this.scgProgramases;
    }
    
    public void setScgProgramases(Set scgProgramases) {
        this.scgProgramases = scgProgramases;
    }




}


