package com.maserven.modelos;
// Generated Nov 20, 2017 3:07:33 PM by Hibernate Tools 4.3.1



/**
 * ScgMotivacion generated by hbm2java
 */
public class ScgMotivacion  implements java.io.Serializable {


     private String scgMotCodigo;
     private char scgMotEstado;
     private String scgMotFrase;

    public ScgMotivacion() {
    }

    public ScgMotivacion(String scgMotCodigo, char scgMotEstado, String scgMotFrase) {
       this.scgMotCodigo = scgMotCodigo;
       this.scgMotEstado = scgMotEstado;
       this.scgMotFrase = scgMotFrase;
    }
   
    public String getScgMotCodigo() {
        return this.scgMotCodigo;
    }
    
    public void setScgMotCodigo(String scgMotCodigo) {
        this.scgMotCodigo = scgMotCodigo;
    }
    public char getScgMotEstado() {
        return this.scgMotEstado;
    }
    
    public void setScgMotEstado(char scgMotEstado) {
        this.scgMotEstado = scgMotEstado;
    }
    public String getScgMotFrase() {
        return this.scgMotFrase;
    }
    
    public void setScgMotFrase(String scgMotFrase) {
        this.scgMotFrase = scgMotFrase;
    }




}


