package com.maserven.modelos;
// Generated Nov 20, 2017 3:07:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ScgMensajes generated by hbm2java
 */
public class ScgMensajes  implements java.io.Serializable {


     private ScgMensajesId id;
     private ScgProgramas scgProgramas;
     private ScgUsuarios scgUsuarios;
     private short scgMenTipo;
     private boolean scgMenAutomatico;
     private short scgMenPrioridad;
     private Date scgMenFecha;
     private String scgMenAsunto;
     private String scgMenTexto;
     private Short scgMenAnioTrx;
     private Integer scgMenNumeroTrx;
     private Set scgMensajesDesesForIscgMensajesDes1 = new HashSet(0);
     private Set scgMensajesDesesForIscgMensajesDes2 = new HashSet(0);
     private Set scgMensajesAdjs = new HashSet(0);

    public ScgMensajes() {
    }

	
    public ScgMensajes(ScgMensajesId id, ScgUsuarios scgUsuarios, short scgMenTipo, boolean scgMenAutomatico, short scgMenPrioridad, Date scgMenFecha, String scgMenAsunto, String scgMenTexto) {
        this.id = id;
        this.scgUsuarios = scgUsuarios;
        this.scgMenTipo = scgMenTipo;
        this.scgMenAutomatico = scgMenAutomatico;
        this.scgMenPrioridad = scgMenPrioridad;
        this.scgMenFecha = scgMenFecha;
        this.scgMenAsunto = scgMenAsunto;
        this.scgMenTexto = scgMenTexto;
    }
    public ScgMensajes(ScgMensajesId id, ScgProgramas scgProgramas, ScgUsuarios scgUsuarios, short scgMenTipo, boolean scgMenAutomatico, short scgMenPrioridad, Date scgMenFecha, String scgMenAsunto, String scgMenTexto, Short scgMenAnioTrx, Integer scgMenNumeroTrx, Set scgMensajesDesesForIscgMensajesDes1, Set scgMensajesDesesForIscgMensajesDes2, Set scgMensajesAdjs) {
       this.id = id;
       this.scgProgramas = scgProgramas;
       this.scgUsuarios = scgUsuarios;
       this.scgMenTipo = scgMenTipo;
       this.scgMenAutomatico = scgMenAutomatico;
       this.scgMenPrioridad = scgMenPrioridad;
       this.scgMenFecha = scgMenFecha;
       this.scgMenAsunto = scgMenAsunto;
       this.scgMenTexto = scgMenTexto;
       this.scgMenAnioTrx = scgMenAnioTrx;
       this.scgMenNumeroTrx = scgMenNumeroTrx;
       this.scgMensajesDesesForIscgMensajesDes1 = scgMensajesDesesForIscgMensajesDes1;
       this.scgMensajesDesesForIscgMensajesDes2 = scgMensajesDesesForIscgMensajesDes2;
       this.scgMensajesAdjs = scgMensajesAdjs;
    }
   
    public ScgMensajesId getId() {
        return this.id;
    }
    
    public void setId(ScgMensajesId id) {
        this.id = id;
    }
    public ScgProgramas getScgProgramas() {
        return this.scgProgramas;
    }
    
    public void setScgProgramas(ScgProgramas scgProgramas) {
        this.scgProgramas = scgProgramas;
    }
    public ScgUsuarios getScgUsuarios() {
        return this.scgUsuarios;
    }
    
    public void setScgUsuarios(ScgUsuarios scgUsuarios) {
        this.scgUsuarios = scgUsuarios;
    }
    public short getScgMenTipo() {
        return this.scgMenTipo;
    }
    
    public void setScgMenTipo(short scgMenTipo) {
        this.scgMenTipo = scgMenTipo;
    }
    public boolean isScgMenAutomatico() {
        return this.scgMenAutomatico;
    }
    
    public void setScgMenAutomatico(boolean scgMenAutomatico) {
        this.scgMenAutomatico = scgMenAutomatico;
    }
    public short getScgMenPrioridad() {
        return this.scgMenPrioridad;
    }
    
    public void setScgMenPrioridad(short scgMenPrioridad) {
        this.scgMenPrioridad = scgMenPrioridad;
    }
    public Date getScgMenFecha() {
        return this.scgMenFecha;
    }
    
    public void setScgMenFecha(Date scgMenFecha) {
        this.scgMenFecha = scgMenFecha;
    }
    public String getScgMenAsunto() {
        return this.scgMenAsunto;
    }
    
    public void setScgMenAsunto(String scgMenAsunto) {
        this.scgMenAsunto = scgMenAsunto;
    }
    public String getScgMenTexto() {
        return this.scgMenTexto;
    }
    
    public void setScgMenTexto(String scgMenTexto) {
        this.scgMenTexto = scgMenTexto;
    }
    public Short getScgMenAnioTrx() {
        return this.scgMenAnioTrx;
    }
    
    public void setScgMenAnioTrx(Short scgMenAnioTrx) {
        this.scgMenAnioTrx = scgMenAnioTrx;
    }
    public Integer getScgMenNumeroTrx() {
        return this.scgMenNumeroTrx;
    }
    
    public void setScgMenNumeroTrx(Integer scgMenNumeroTrx) {
        this.scgMenNumeroTrx = scgMenNumeroTrx;
    }
    public Set getScgMensajesDesesForIscgMensajesDes1() {
        return this.scgMensajesDesesForIscgMensajesDes1;
    }
    
    public void setScgMensajesDesesForIscgMensajesDes1(Set scgMensajesDesesForIscgMensajesDes1) {
        this.scgMensajesDesesForIscgMensajesDes1 = scgMensajesDesesForIscgMensajesDes1;
    }
    public Set getScgMensajesDesesForIscgMensajesDes2() {
        return this.scgMensajesDesesForIscgMensajesDes2;
    }
    
    public void setScgMensajesDesesForIscgMensajesDes2(Set scgMensajesDesesForIscgMensajesDes2) {
        this.scgMensajesDesesForIscgMensajesDes2 = scgMensajesDesesForIscgMensajesDes2;
    }
    public Set getScgMensajesAdjs() {
        return this.scgMensajesAdjs;
    }
    
    public void setScgMensajesAdjs(Set scgMensajesAdjs) {
        this.scgMensajesAdjs = scgMensajesAdjs;
    }




}


