package com.maserven.modelos;
// Generated Nov 20, 2017 3:07:33 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ScgMensajesDes generated by hbm2java
 */
public class ScgMensajesDes  implements java.io.Serializable {


     private ScgMensajesDesId id;
     private ScgMensajes scgMensajesByIscgMensajesDes1;
     private ScgMensajes scgMensajesByIscgMensajesDes2;
     private String scgDesCodigoEpr;
     private boolean scgDesCopia;
     private boolean scgDesEntregado;
     private Date scgDesFechaEntregado;
     private boolean scgDesLeido;
     private Date scgDesFechaLeido;

    public ScgMensajesDes() {
    }

	
    public ScgMensajesDes(ScgMensajesDesId id, ScgMensajes scgMensajesByIscgMensajesDes1, ScgMensajes scgMensajesByIscgMensajesDes2, boolean scgDesCopia, boolean scgDesEntregado, boolean scgDesLeido) {
        this.id = id;
        this.scgMensajesByIscgMensajesDes1 = scgMensajesByIscgMensajesDes1;
        this.scgMensajesByIscgMensajesDes2 = scgMensajesByIscgMensajesDes2;
        this.scgDesCopia = scgDesCopia;
        this.scgDesEntregado = scgDesEntregado;
        this.scgDesLeido = scgDesLeido;
    }
    public ScgMensajesDes(ScgMensajesDesId id, ScgMensajes scgMensajesByIscgMensajesDes1, ScgMensajes scgMensajesByIscgMensajesDes2, String scgDesCodigoEpr, boolean scgDesCopia, boolean scgDesEntregado, Date scgDesFechaEntregado, boolean scgDesLeido, Date scgDesFechaLeido) {
       this.id = id;
       this.scgMensajesByIscgMensajesDes1 = scgMensajesByIscgMensajesDes1;
       this.scgMensajesByIscgMensajesDes2 = scgMensajesByIscgMensajesDes2;
       this.scgDesCodigoEpr = scgDesCodigoEpr;
       this.scgDesCopia = scgDesCopia;
       this.scgDesEntregado = scgDesEntregado;
       this.scgDesFechaEntregado = scgDesFechaEntregado;
       this.scgDesLeido = scgDesLeido;
       this.scgDesFechaLeido = scgDesFechaLeido;
    }
   
    public ScgMensajesDesId getId() {
        return this.id;
    }
    
    public void setId(ScgMensajesDesId id) {
        this.id = id;
    }
    public ScgMensajes getScgMensajesByIscgMensajesDes1() {
        return this.scgMensajesByIscgMensajesDes1;
    }
    
    public void setScgMensajesByIscgMensajesDes1(ScgMensajes scgMensajesByIscgMensajesDes1) {
        this.scgMensajesByIscgMensajesDes1 = scgMensajesByIscgMensajesDes1;
    }
    public ScgMensajes getScgMensajesByIscgMensajesDes2() {
        return this.scgMensajesByIscgMensajesDes2;
    }
    
    public void setScgMensajesByIscgMensajesDes2(ScgMensajes scgMensajesByIscgMensajesDes2) {
        this.scgMensajesByIscgMensajesDes2 = scgMensajesByIscgMensajesDes2;
    }
    public String getScgDesCodigoEpr() {
        return this.scgDesCodigoEpr;
    }
    
    public void setScgDesCodigoEpr(String scgDesCodigoEpr) {
        this.scgDesCodigoEpr = scgDesCodigoEpr;
    }
    public boolean isScgDesCopia() {
        return this.scgDesCopia;
    }
    
    public void setScgDesCopia(boolean scgDesCopia) {
        this.scgDesCopia = scgDesCopia;
    }
    public boolean isScgDesEntregado() {
        return this.scgDesEntregado;
    }
    
    public void setScgDesEntregado(boolean scgDesEntregado) {
        this.scgDesEntregado = scgDesEntregado;
    }
    public Date getScgDesFechaEntregado() {
        return this.scgDesFechaEntregado;
    }
    
    public void setScgDesFechaEntregado(Date scgDesFechaEntregado) {
        this.scgDesFechaEntregado = scgDesFechaEntregado;
    }
    public boolean isScgDesLeido() {
        return this.scgDesLeido;
    }
    
    public void setScgDesLeido(boolean scgDesLeido) {
        this.scgDesLeido = scgDesLeido;
    }
    public Date getScgDesFechaLeido() {
        return this.scgDesFechaLeido;
    }
    
    public void setScgDesFechaLeido(Date scgDesFechaLeido) {
        this.scgDesFechaLeido = scgDesFechaLeido;
    }




}


