package com.maserven.modelos;
// Generated Nov 20, 2017 3:07:33 PM by Hibernate Tools 4.3.1



/**
 * ScgProvinciasCiuId generated by hbm2java
 */
public class ScgProvinciasCiuId  implements java.io.Serializable {


     private short scgProCodigo;
     private short scgCiuCodigo;

    public ScgProvinciasCiuId() {
    }

    public ScgProvinciasCiuId(short scgProCodigo, short scgCiuCodigo) {
       this.scgProCodigo = scgProCodigo;
       this.scgCiuCodigo = scgCiuCodigo;
    }
   
    public short getScgProCodigo() {
        return this.scgProCodigo;
    }
    
    public void setScgProCodigo(short scgProCodigo) {
        this.scgProCodigo = scgProCodigo;
    }
    public short getScgCiuCodigo() {
        return this.scgCiuCodigo;
    }
    
    public void setScgCiuCodigo(short scgCiuCodigo) {
        this.scgCiuCodigo = scgCiuCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ScgProvinciasCiuId) ) return false;
		 ScgProvinciasCiuId castOther = ( ScgProvinciasCiuId ) other; 
         
		 return (this.getScgProCodigo()==castOther.getScgProCodigo())
 && (this.getScgCiuCodigo()==castOther.getScgCiuCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getScgProCodigo();
         result = 37 * result + this.getScgCiuCodigo();
         return result;
   }   


}


