package com.maserven.modelos;
// Generated Nov 20, 2017 3:07:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ScgProgramas generated by hbm2java
 */
public class ScgProgramas  implements java.io.Serializable {


     private String scgPrgCodigo;
     private ScgModulos scgModulos;
     private String scgPrgDescripcion;
     private String scgPrgAbreviatura;
     private char scgPrgTipo;
     private String scgPrgObjeto;
     private String scgPrgPrograma;
     private Set scgPerfilesDets = new HashSet(0);
     private Set scgReporteses = new HashSet(0);
     private Set scgMensajeses = new HashSet(0);

    public ScgProgramas() {
    }

	
    public ScgProgramas(String scgPrgCodigo, String scgPrgDescripcion, String scgPrgAbreviatura, char scgPrgTipo, String scgPrgObjeto, String scgPrgPrograma) {
        this.scgPrgCodigo = scgPrgCodigo;
        this.scgPrgDescripcion = scgPrgDescripcion;
        this.scgPrgAbreviatura = scgPrgAbreviatura;
        this.scgPrgTipo = scgPrgTipo;
        this.scgPrgObjeto = scgPrgObjeto;
        this.scgPrgPrograma = scgPrgPrograma;
    }
    public ScgProgramas(String scgPrgCodigo, ScgModulos scgModulos, String scgPrgDescripcion, String scgPrgAbreviatura, char scgPrgTipo, String scgPrgObjeto, String scgPrgPrograma, Set scgPerfilesDets, Set scgReporteses, Set scgMensajeses) {
       this.scgPrgCodigo = scgPrgCodigo;
       this.scgModulos = scgModulos;
       this.scgPrgDescripcion = scgPrgDescripcion;
       this.scgPrgAbreviatura = scgPrgAbreviatura;
       this.scgPrgTipo = scgPrgTipo;
       this.scgPrgObjeto = scgPrgObjeto;
       this.scgPrgPrograma = scgPrgPrograma;
       this.scgPerfilesDets = scgPerfilesDets;
       this.scgReporteses = scgReporteses;
       this.scgMensajeses = scgMensajeses;
    }
   
    public String getScgPrgCodigo() {
        return this.scgPrgCodigo;
    }
    
    public void setScgPrgCodigo(String scgPrgCodigo) {
        this.scgPrgCodigo = scgPrgCodigo;
    }
    public ScgModulos getScgModulos() {
        return this.scgModulos;
    }
    
    public void setScgModulos(ScgModulos scgModulos) {
        this.scgModulos = scgModulos;
    }
    public String getScgPrgDescripcion() {
        return this.scgPrgDescripcion;
    }
    
    public void setScgPrgDescripcion(String scgPrgDescripcion) {
        this.scgPrgDescripcion = scgPrgDescripcion;
    }
    public String getScgPrgAbreviatura() {
        return this.scgPrgAbreviatura;
    }
    
    public void setScgPrgAbreviatura(String scgPrgAbreviatura) {
        this.scgPrgAbreviatura = scgPrgAbreviatura;
    }
    public char getScgPrgTipo() {
        return this.scgPrgTipo;
    }
    
    public void setScgPrgTipo(char scgPrgTipo) {
        this.scgPrgTipo = scgPrgTipo;
    }
    public String getScgPrgObjeto() {
        return this.scgPrgObjeto;
    }
    
    public void setScgPrgObjeto(String scgPrgObjeto) {
        this.scgPrgObjeto = scgPrgObjeto;
    }
    public String getScgPrgPrograma() {
        return this.scgPrgPrograma;
    }
    
    public void setScgPrgPrograma(String scgPrgPrograma) {
        this.scgPrgPrograma = scgPrgPrograma;
    }
    public Set getScgPerfilesDets() {
        return this.scgPerfilesDets;
    }
    
    public void setScgPerfilesDets(Set scgPerfilesDets) {
        this.scgPerfilesDets = scgPerfilesDets;
    }
    public Set getScgReporteses() {
        return this.scgReporteses;
    }
    
    public void setScgReporteses(Set scgReporteses) {
        this.scgReporteses = scgReporteses;
    }
    public Set getScgMensajeses() {
        return this.scgMensajeses;
    }
    
    public void setScgMensajeses(Set scgMensajeses) {
        this.scgMensajeses = scgMensajeses;
    }




}


