package com.maserven.modelos;
// Generated Nov 20, 2017 3:07:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ScgProvinciasCiu generated by hbm2java
 */
public class ScgProvinciasCiu  implements java.io.Serializable {


     private ScgProvinciasCiuId id;
     private ScgProvincias scgProvincias;
     private String scgCiuDescripcion;
     private Set scgEmpresases = new HashSet(0);

    public ScgProvinciasCiu() {
    }

	
    public ScgProvinciasCiu(ScgProvinciasCiuId id, ScgProvincias scgProvincias, String scgCiuDescripcion) {
        this.id = id;
        this.scgProvincias = scgProvincias;
        this.scgCiuDescripcion = scgCiuDescripcion;
    }
    public ScgProvinciasCiu(ScgProvinciasCiuId id, ScgProvincias scgProvincias, String scgCiuDescripcion, Set scgEmpresases) {
       this.id = id;
       this.scgProvincias = scgProvincias;
       this.scgCiuDescripcion = scgCiuDescripcion;
       this.scgEmpresases = scgEmpresases;
    }
   
    public ScgProvinciasCiuId getId() {
        return this.id;
    }
    
    public void setId(ScgProvinciasCiuId id) {
        this.id = id;
    }
    public ScgProvincias getScgProvincias() {
        return this.scgProvincias;
    }
    
    public void setScgProvincias(ScgProvincias scgProvincias) {
        this.scgProvincias = scgProvincias;
    }
    public String getScgCiuDescripcion() {
        return this.scgCiuDescripcion;
    }
    
    public void setScgCiuDescripcion(String scgCiuDescripcion) {
        this.scgCiuDescripcion = scgCiuDescripcion;
    }
    public Set getScgEmpresases() {
        return this.scgEmpresases;
    }
    
    public void setScgEmpresases(Set scgEmpresases) {
        this.scgEmpresases = scgEmpresases;
    }




}


