package com.maserven.modelos;
// Generated Nov 20, 2017 3:07:33 PM by Hibernate Tools 4.3.1



/**
 * ScgPerfilesDetId generated by hbm2java
 */
public class ScgPerfilesDetId  implements java.io.Serializable {


     private String scgPerCodigo;
     private String scgPrgCodigo;

    public ScgPerfilesDetId() {
    }

    public ScgPerfilesDetId(String scgPerCodigo, String scgPrgCodigo) {
       this.scgPerCodigo = scgPerCodigo;
       this.scgPrgCodigo = scgPrgCodigo;
    }
   
    public String getScgPerCodigo() {
        return this.scgPerCodigo;
    }
    
    public void setScgPerCodigo(String scgPerCodigo) {
        this.scgPerCodigo = scgPerCodigo;
    }
    public String getScgPrgCodigo() {
        return this.scgPrgCodigo;
    }
    
    public void setScgPrgCodigo(String scgPrgCodigo) {
        this.scgPrgCodigo = scgPrgCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ScgPerfilesDetId) ) return false;
		 ScgPerfilesDetId castOther = ( ScgPerfilesDetId ) other; 
         
		 return ( (this.getScgPerCodigo()==castOther.getScgPerCodigo()) || ( this.getScgPerCodigo()!=null && castOther.getScgPerCodigo()!=null && this.getScgPerCodigo().equals(castOther.getScgPerCodigo()) ) )
 && ( (this.getScgPrgCodigo()==castOther.getScgPrgCodigo()) || ( this.getScgPrgCodigo()!=null && castOther.getScgPrgCodigo()!=null && this.getScgPrgCodigo().equals(castOther.getScgPrgCodigo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getScgPerCodigo() == null ? 0 : this.getScgPerCodigo().hashCode() );
         result = 37 * result + ( getScgPrgCodigo() == null ? 0 : this.getScgPrgCodigo().hashCode() );
         return result;
   }   


}


