package com.maserven.modelos;
// Generated Nov 20, 2017 3:07:33 PM by Hibernate Tools 4.3.1



/**
 * ScgPerfilesDet generated by hbm2java
 */
public class ScgPerfilesDet  implements java.io.Serializable {


     private ScgPerfilesDetId id;
     private ScgPerfilesCab scgPerfilesCab;
     private ScgProgramas scgProgramas;
     private boolean scgAccNuevo;
     private boolean scgAccModificar;
     private boolean scgAccAnular;
     private boolean scgAccProcesar;
     private boolean scgAccImprimir;
     private boolean scgAccConsultar;

    public ScgPerfilesDet() {
    }

    public ScgPerfilesDet(ScgPerfilesDetId id, ScgPerfilesCab scgPerfilesCab, ScgProgramas scgProgramas, boolean scgAccNuevo, boolean scgAccModificar, boolean scgAccAnular, boolean scgAccProcesar, boolean scgAccImprimir, boolean scgAccConsultar) {
       this.id = id;
       this.scgPerfilesCab = scgPerfilesCab;
       this.scgProgramas = scgProgramas;
       this.scgAccNuevo = scgAccNuevo;
       this.scgAccModificar = scgAccModificar;
       this.scgAccAnular = scgAccAnular;
       this.scgAccProcesar = scgAccProcesar;
       this.scgAccImprimir = scgAccImprimir;
       this.scgAccConsultar = scgAccConsultar;
    }
   
    public ScgPerfilesDetId getId() {
        return this.id;
    }
    
    public void setId(ScgPerfilesDetId id) {
        this.id = id;
    }
    public ScgPerfilesCab getScgPerfilesCab() {
        return this.scgPerfilesCab;
    }
    
    public void setScgPerfilesCab(ScgPerfilesCab scgPerfilesCab) {
        this.scgPerfilesCab = scgPerfilesCab;
    }
    public ScgProgramas getScgProgramas() {
        return this.scgProgramas;
    }
    
    public void setScgProgramas(ScgProgramas scgProgramas) {
        this.scgProgramas = scgProgramas;
    }
    public boolean isScgAccNuevo() {
        return this.scgAccNuevo;
    }
    
    public void setScgAccNuevo(boolean scgAccNuevo) {
        this.scgAccNuevo = scgAccNuevo;
    }
    public boolean isScgAccModificar() {
        return this.scgAccModificar;
    }
    
    public void setScgAccModificar(boolean scgAccModificar) {
        this.scgAccModificar = scgAccModificar;
    }
    public boolean isScgAccAnular() {
        return this.scgAccAnular;
    }
    
    public void setScgAccAnular(boolean scgAccAnular) {
        this.scgAccAnular = scgAccAnular;
    }
    public boolean isScgAccProcesar() {
        return this.scgAccProcesar;
    }
    
    public void setScgAccProcesar(boolean scgAccProcesar) {
        this.scgAccProcesar = scgAccProcesar;
    }
    public boolean isScgAccImprimir() {
        return this.scgAccImprimir;
    }
    
    public void setScgAccImprimir(boolean scgAccImprimir) {
        this.scgAccImprimir = scgAccImprimir;
    }
    public boolean isScgAccConsultar() {
        return this.scgAccConsultar;
    }
    
    public void setScgAccConsultar(boolean scgAccConsultar) {
        this.scgAccConsultar = scgAccConsultar;
    }




}


