package com.maserven.modelos;
// Generated Nov 20, 2017 3:07:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ScgProvincias generated by hbm2java
 */
public class ScgProvincias  implements java.io.Serializable {


     private short scgProCodigo;
     private String scgProDescripcion;
     private Set scgProvinciasCius = new HashSet(0);

    public ScgProvincias() {
    }

	
    public ScgProvincias(short scgProCodigo, String scgProDescripcion) {
        this.scgProCodigo = scgProCodigo;
        this.scgProDescripcion = scgProDescripcion;
    }
    public ScgProvincias(short scgProCodigo, String scgProDescripcion, Set scgProvinciasCius) {
       this.scgProCodigo = scgProCodigo;
       this.scgProDescripcion = scgProDescripcion;
       this.scgProvinciasCius = scgProvinciasCius;
    }
   
    public short getScgProCodigo() {
        return this.scgProCodigo;
    }
    
    public void setScgProCodigo(short scgProCodigo) {
        this.scgProCodigo = scgProCodigo;
    }
    public String getScgProDescripcion() {
        return this.scgProDescripcion;
    }
    
    public void setScgProDescripcion(String scgProDescripcion) {
        this.scgProDescripcion = scgProDescripcion;
    }
    public Set getScgProvinciasCius() {
        return this.scgProvinciasCius;
    }
    
    public void setScgProvinciasCius(Set scgProvinciasCius) {
        this.scgProvinciasCius = scgProvinciasCius;
    }




}


