package com.maserven.modelos;
// Generated Nov 20, 2017 3:07:33 PM by Hibernate Tools 4.3.1



/**
 * ScgReportesId generated by hbm2java
 */
public class ScgReportesId  implements java.io.Serializable {


     private String scgPrgCodigo;
     private String scgRepCodigo;

    public ScgReportesId() {
    }

    public ScgReportesId(String scgPrgCodigo, String scgRepCodigo) {
       this.scgPrgCodigo = scgPrgCodigo;
       this.scgRepCodigo = scgRepCodigo;
    }
   
    public String getScgPrgCodigo() {
        return this.scgPrgCodigo;
    }
    
    public void setScgPrgCodigo(String scgPrgCodigo) {
        this.scgPrgCodigo = scgPrgCodigo;
    }
    public String getScgRepCodigo() {
        return this.scgRepCodigo;
    }
    
    public void setScgRepCodigo(String scgRepCodigo) {
        this.scgRepCodigo = scgRepCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ScgReportesId) ) return false;
		 ScgReportesId castOther = ( ScgReportesId ) other; 
         
		 return ( (this.getScgPrgCodigo()==castOther.getScgPrgCodigo()) || ( this.getScgPrgCodigo()!=null && castOther.getScgPrgCodigo()!=null && this.getScgPrgCodigo().equals(castOther.getScgPrgCodigo()) ) )
 && ( (this.getScgRepCodigo()==castOther.getScgRepCodigo()) || ( this.getScgRepCodigo()!=null && castOther.getScgRepCodigo()!=null && this.getScgRepCodigo().equals(castOther.getScgRepCodigo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getScgPrgCodigo() == null ? 0 : this.getScgPrgCodigo().hashCode() );
         result = 37 * result + ( getScgRepCodigo() == null ? 0 : this.getScgRepCodigo().hashCode() );
         return result;
   }   


}


