package com.maserven.modelos;
// Generated Nov 20, 2017 3:07:33 PM by Hibernate Tools 4.3.1



/**
 * ScgReportes generated by hbm2java
 */
public class ScgReportes  implements java.io.Serializable {


     private ScgReportesId id;
     private ScgProgramas scgProgramas;
     private String scgRepDescripcion;
     private String scgRepObjeto;
     private short scgRepTipo;
     private boolean scgRepPrincipal;
     private boolean scgRepActivo;

    public ScgReportes() {
    }

    public ScgReportes(ScgReportesId id, ScgProgramas scgProgramas, String scgRepDescripcion, String scgRepObjeto, short scgRepTipo, boolean scgRepPrincipal, boolean scgRepActivo) {
       this.id = id;
       this.scgProgramas = scgProgramas;
       this.scgRepDescripcion = scgRepDescripcion;
       this.scgRepObjeto = scgRepObjeto;
       this.scgRepTipo = scgRepTipo;
       this.scgRepPrincipal = scgRepPrincipal;
       this.scgRepActivo = scgRepActivo;
    }
   
    public ScgReportesId getId() {
        return this.id;
    }
    
    public void setId(ScgReportesId id) {
        this.id = id;
    }
    public ScgProgramas getScgProgramas() {
        return this.scgProgramas;
    }
    
    public void setScgProgramas(ScgProgramas scgProgramas) {
        this.scgProgramas = scgProgramas;
    }
    public String getScgRepDescripcion() {
        return this.scgRepDescripcion;
    }
    
    public void setScgRepDescripcion(String scgRepDescripcion) {
        this.scgRepDescripcion = scgRepDescripcion;
    }
    public String getScgRepObjeto() {
        return this.scgRepObjeto;
    }
    
    public void setScgRepObjeto(String scgRepObjeto) {
        this.scgRepObjeto = scgRepObjeto;
    }
    public short getScgRepTipo() {
        return this.scgRepTipo;
    }
    
    public void setScgRepTipo(short scgRepTipo) {
        this.scgRepTipo = scgRepTipo;
    }
    public boolean isScgRepPrincipal() {
        return this.scgRepPrincipal;
    }
    
    public void setScgRepPrincipal(boolean scgRepPrincipal) {
        this.scgRepPrincipal = scgRepPrincipal;
    }
    public boolean isScgRepActivo() {
        return this.scgRepActivo;
    }
    
    public void setScgRepActivo(boolean scgRepActivo) {
        this.scgRepActivo = scgRepActivo;
    }




}


