package com.maserven.modelos;
// Generated Nov 20, 2017 3:07:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ScgUsuarios generated by hbm2java
 */
public class ScgUsuarios  implements java.io.Serializable {


     private String scgUsuCodigo;
     private String scgUsuClave;
     private String scgUsuApellidos;
     private String scgUsuNombres;
     private char scgUsuEstado;
     private char scgUsuTipo;
     private char scgUsuFuncion;
     private String scgUsuEmail;
     private Date scgUsuActualizaFec;
     private String scgUsuActualizaUsr;
     private Date scgUsuCreacionFec;
     private String scgUsuCreacionUsr;
     private boolean scgUsuValidaSesion;
     private Set scgMensajeses = new HashSet(0);
     private Set scgUsuariosEprs = new HashSet(0);

    public ScgUsuarios() {
    }

	
    public ScgUsuarios(String scgUsuCodigo, String scgUsuClave, String scgUsuApellidos, String scgUsuNombres, char scgUsuEstado, char scgUsuTipo, char scgUsuFuncion, String scgUsuEmail, Date scgUsuActualizaFec, String scgUsuActualizaUsr, Date scgUsuCreacionFec, String scgUsuCreacionUsr, boolean scgUsuValidaSesion) {
        this.scgUsuCodigo = scgUsuCodigo;
        this.scgUsuClave = scgUsuClave;
        this.scgUsuApellidos = scgUsuApellidos;
        this.scgUsuNombres = scgUsuNombres;
        this.scgUsuEstado = scgUsuEstado;
        this.scgUsuTipo = scgUsuTipo;
        this.scgUsuFuncion = scgUsuFuncion;
        this.scgUsuEmail = scgUsuEmail;
        this.scgUsuActualizaFec = scgUsuActualizaFec;
        this.scgUsuActualizaUsr = scgUsuActualizaUsr;
        this.scgUsuCreacionFec = scgUsuCreacionFec;
        this.scgUsuCreacionUsr = scgUsuCreacionUsr;
        this.scgUsuValidaSesion = scgUsuValidaSesion;
    }
    public ScgUsuarios(String scgUsuCodigo, String scgUsuClave, String scgUsuApellidos, String scgUsuNombres, char scgUsuEstado, char scgUsuTipo, char scgUsuFuncion, String scgUsuEmail, Date scgUsuActualizaFec, String scgUsuActualizaUsr, Date scgUsuCreacionFec, String scgUsuCreacionUsr, boolean scgUsuValidaSesion, Set scgMensajeses, Set scgUsuariosEprs) {
       this.scgUsuCodigo = scgUsuCodigo;
       this.scgUsuClave = scgUsuClave;
       this.scgUsuApellidos = scgUsuApellidos;
       this.scgUsuNombres = scgUsuNombres;
       this.scgUsuEstado = scgUsuEstado;
       this.scgUsuTipo = scgUsuTipo;
       this.scgUsuFuncion = scgUsuFuncion;
       this.scgUsuEmail = scgUsuEmail;
       this.scgUsuActualizaFec = scgUsuActualizaFec;
       this.scgUsuActualizaUsr = scgUsuActualizaUsr;
       this.scgUsuCreacionFec = scgUsuCreacionFec;
       this.scgUsuCreacionUsr = scgUsuCreacionUsr;
       this.scgUsuValidaSesion = scgUsuValidaSesion;
       this.scgMensajeses = scgMensajeses;
       this.scgUsuariosEprs = scgUsuariosEprs;
    }
   
    public String getScgUsuCodigo() {
        return this.scgUsuCodigo;
    }
    
    public void setScgUsuCodigo(String scgUsuCodigo) {
        this.scgUsuCodigo = scgUsuCodigo;
    }
    public String getScgUsuClave() {
        return this.scgUsuClave;
    }
    
    public void setScgUsuClave(String scgUsuClave) {
        this.scgUsuClave = scgUsuClave;
    }
    public String getScgUsuApellidos() {
        return this.scgUsuApellidos;
    }
    
    public void setScgUsuApellidos(String scgUsuApellidos) {
        this.scgUsuApellidos = scgUsuApellidos;
    }
    public String getScgUsuNombres() {
        return this.scgUsuNombres;
    }
    
    public void setScgUsuNombres(String scgUsuNombres) {
        this.scgUsuNombres = scgUsuNombres;
    }
    public char getScgUsuEstado() {
        return this.scgUsuEstado;
    }
    
    public void setScgUsuEstado(char scgUsuEstado) {
        this.scgUsuEstado = scgUsuEstado;
    }
    public char getScgUsuTipo() {
        return this.scgUsuTipo;
    }
    
    public void setScgUsuTipo(char scgUsuTipo) {
        this.scgUsuTipo = scgUsuTipo;
    }
    public char getScgUsuFuncion() {
        return this.scgUsuFuncion;
    }
    
    public void setScgUsuFuncion(char scgUsuFuncion) {
        this.scgUsuFuncion = scgUsuFuncion;
    }
    public String getScgUsuEmail() {
        return this.scgUsuEmail;
    }
    
    public void setScgUsuEmail(String scgUsuEmail) {
        this.scgUsuEmail = scgUsuEmail;
    }
    public Date getScgUsuActualizaFec() {
        return this.scgUsuActualizaFec;
    }
    
    public void setScgUsuActualizaFec(Date scgUsuActualizaFec) {
        this.scgUsuActualizaFec = scgUsuActualizaFec;
    }
    public String getScgUsuActualizaUsr() {
        return this.scgUsuActualizaUsr;
    }
    
    public void setScgUsuActualizaUsr(String scgUsuActualizaUsr) {
        this.scgUsuActualizaUsr = scgUsuActualizaUsr;
    }
    public Date getScgUsuCreacionFec() {
        return this.scgUsuCreacionFec;
    }
    
    public void setScgUsuCreacionFec(Date scgUsuCreacionFec) {
        this.scgUsuCreacionFec = scgUsuCreacionFec;
    }
    public String getScgUsuCreacionUsr() {
        return this.scgUsuCreacionUsr;
    }
    
    public void setScgUsuCreacionUsr(String scgUsuCreacionUsr) {
        this.scgUsuCreacionUsr = scgUsuCreacionUsr;
    }
    public boolean isScgUsuValidaSesion() {
        return this.scgUsuValidaSesion;
    }
    
    public void setScgUsuValidaSesion(boolean scgUsuValidaSesion) {
        this.scgUsuValidaSesion = scgUsuValidaSesion;
    }
    public Set getScgMensajeses() {
        return this.scgMensajeses;
    }
    
    public void setScgMensajeses(Set scgMensajeses) {
        this.scgMensajeses = scgMensajeses;
    }
    public Set getScgUsuariosEprs() {
        return this.scgUsuariosEprs;
    }
    
    public void setScgUsuariosEprs(Set scgUsuariosEprs) {
        this.scgUsuariosEprs = scgUsuariosEprs;
    }




}


