package com.maserven.modelos;
// Generated Nov 20, 2017 3:07:33 PM by Hibernate Tools 4.3.1



/**
 * ScgUsuariosEprId generated by hbm2java
 */
public class ScgUsuariosEprId  implements java.io.Serializable {


     private String scgUsuCodigo;
     private String scgEprCodigo;

    public ScgUsuariosEprId() {
    }

    public ScgUsuariosEprId(String scgUsuCodigo, String scgEprCodigo) {
       this.scgUsuCodigo = scgUsuCodigo;
       this.scgEprCodigo = scgEprCodigo;
    }
   
    public String getScgUsuCodigo() {
        return this.scgUsuCodigo;
    }
    
    public void setScgUsuCodigo(String scgUsuCodigo) {
        this.scgUsuCodigo = scgUsuCodigo;
    }
    public String getScgEprCodigo() {
        return this.scgEprCodigo;
    }
    
    public void setScgEprCodigo(String scgEprCodigo) {
        this.scgEprCodigo = scgEprCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ScgUsuariosEprId) ) return false;
		 ScgUsuariosEprId castOther = ( ScgUsuariosEprId ) other; 
         
		 return ( (this.getScgUsuCodigo()==castOther.getScgUsuCodigo()) || ( this.getScgUsuCodigo()!=null && castOther.getScgUsuCodigo()!=null && this.getScgUsuCodigo().equals(castOther.getScgUsuCodigo()) ) )
 && ( (this.getScgEprCodigo()==castOther.getScgEprCodigo()) || ( this.getScgEprCodigo()!=null && castOther.getScgEprCodigo()!=null && this.getScgEprCodigo().equals(castOther.getScgEprCodigo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getScgUsuCodigo() == null ? 0 : this.getScgUsuCodigo().hashCode() );
         result = 37 * result + ( getScgEprCodigo() == null ? 0 : this.getScgEprCodigo().hashCode() );
         return result;
   }   


}


